name: Build Embedded Snapshots

on:
  push:
    branches: [main]
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        swift:
          - version: 6.4.x-snapshot-2026-08-14
            wasm-sdk-url: https://download.swift.org/swift-6.4.x-branch/wasm-sdk/swift-6.4.x-DEVELOPMENT-SNAPSHOT-2026-08-14-a/swift-6.4.x-DEVELOPMENT-SNAPSHOT-2026-08-14-a_wasm.artifactbundle.tar.gz
            wasm-sdk-checksum: 11fabfac6804222569d330fbbb5fa34eef736abda46790e723ac73b256fd1c7a
            wasm_sdk_id: swift-6.4.x-DEVELOPMENT-SNAPSHOT-2026-08-14-a_wasm-embedded

          - version: main-snapshot-2026-08-21
            wasm-sdk-url: https://download.swift.org/development/wasm-sdk/swift-DEVELOPMENT-SNAPSHOT-2026-08-21-a/swift-DEVELOPMENT-SNAPSHOT-2026-08-21-a_wasm.artifactbundle.tar.gz
            wasm-sdk-checksum: 19cb319e07661625928f43df3fddabfa9ca4821a3215f5f5a7592c06f3d632e3
            wasm_sdk_id: swift-DEVELOPMENT-SNAPSHOT-2026-08-21-a_wasm-embedded
        examples:
          - Examples/Swiftle
          - Examples/Basic

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift.version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ${{ matrix.examples }}/pnpm-lock.yaml

      - name: Install Swift WASM SDK
        run: swift sdk install ${{ matrix.swift.wasm-sdk-url }} --checksum ${{ matrix.swift.wasm-sdk-checksum }}

      - name: Install dependencies
        working-directory: ${{ matrix.examples }}
        run: swift package resolve && pnpm install

      - name: Build
        working-directory: ${{ matrix.examples }}
        run: pnpm build
